[auth]
enabled = true
site_url = "https://agentflow-inky.vercel.app"
additional_redirect_urls = [
  "https://agentflow-inky.vercel.app/auth/callback",
  "https://agentflow-inky.vercel.app/**"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.external.google]
enabled = true
client_id = "89182633418-9mcj8uptevu2ifkl6uctkb7p7qr3oo8d.apps.googleusercontent.com"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "https://fsxdduvwshirrheenmag.supabase.co/auth/v1/callback"
